/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import proyectofinal.BaseDatos;
import proyectofinal.MenuPpal;
import proyectofinal.Producto;

/**
 *
 * @author David
 */
public class ConsProducto extends javax.swing.JFrame {

    /**
     * Creates new form ConsProducto
     */
    public MenuPpal menuppal;

    public ConsProducto(MenuPpal menuppal) {
        this.menuppal = menuppal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsulta = new javax.swing.JTable();
        btAtrasCs = new javax.swing.JButton();
        btModCs = new javax.swing.JButton();
        btDelCs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripción", "Existencia", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jtConsulta);

        btAtrasCs.setText("Atras");
        btAtrasCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtrasCsActionPerformed(evt);
            }
        });

        btModCs.setText("Modificar");
        btModCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModCsActionPerformed(evt);
            }
        });

        btDelCs.setText("Eliminar");
        btDelCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelCsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel1.setText("Consulta General");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAtrasCs)
                                .addGap(311, 311, 311)
                                .addComponent(btModCs)
                                .addGap(42, 42, 42)
                                .addComponent(btDelCs))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAtrasCs)
                    .addComponent(btModCs)
                    .addComponent(btDelCs))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btAtrasCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtrasCsActionPerformed
        this.setVisible(false);
        menuppal.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btAtrasCsActionPerformed

    private void btModCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModCsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btModCsActionPerformed

    private void btDelCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelCsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDelCsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Mostrar();
        // Metodo que pasa el modelo a la tabla 
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtrasCs;
    private javax.swing.JButton btDelCs;
    private javax.swing.JButton btModCs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtConsulta;
    // End of variables declaration//GEN-END:variables

    private BaseDatos bd;
    private DefaultTableModel modelo = new DefaultTableModel();

    private void Mostrar() {
        generaMatrizDatos();
    }

    /**
     * @return the bd
     */
    public BaseDatos getBd() {
        return bd;
    }

    /**
     * @param bd the bd to set
     */
    public void setBd(BaseDatos bd) {
        this.bd = bd;
    }

    /**
     * @return the modelo
     */
    public DefaultTableModel getModelo() {
        return modelo;
    }

    /**
     * @param modelo the modelo to set
     */
    public void setModelo(DefaultTableModel modelo) {
        this.modelo = modelo;
    }

    public void generaMatrizDatos() {
        ArrayList lista = bd.getProductos();
        Object[][] matriz = new Object[lista.size()][4];
        for (int i = 0; i < lista.size(); i++) {
            Producto cTemp = (Producto) lista.get(i);

            matriz[i][0] = cTemp.getCodProducto();
            matriz[i][1] = cTemp.getDescProducto();
            matriz[i][2] = cTemp.getExstProducto();
            matriz[i][3] = cTemp.getValrProducto();

        }
        String[] identificadores = new String[]{"Codigo", "Decripción", "Existencia", "Valor"};
        modelo.setDataVector(matriz, identificadores);
        jtConsulta.setModel(modelo);

    }

}
